
import type { MenuCategory } from './types';

export const MENU_DATA: MenuCategory[] = [
  {
    id: 'breakfast',
    name: 'Break Fast',
    image: 'https://c.ndtvimg.com/2022-03/0ehrs0c_egg-paratha_625x300_10_March_22.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=675',
    items: [
      { name: 'Onion Paratha', price: 100, description: 'Whole wheat flatbread stuffed with spiced onions.' },
      { name: 'Aloo Paratha', price: 100, description: 'Popular Indian flatbread stuffed with a delicious spiced potato mixture.' },
      { name: 'Paneer Paratha', price: 120, isBestseller: true, description: 'A crowd-favorite! Soft flatbread with a savory, spiced paneer filling.' },
      { name: 'Methi Paratha', price: 100 },
      { name: 'Veg. Sandwich', price: 70 },
      { name: 'Bombay Sandwich', price: 60 },
      { name: 'Cheese Sandwich', price: 80 },
      { name: 'Veg. Grilled Sandwich', price: 90 },
      { name: 'Grilled Cheese Sandwich', price: 100 },
      { name: 'Grilled Veg. Cheese Sandwich', price: 100 },
    ],
  },
  {
    id: 'soup',
    name: 'Soup',
    image: 'https://www.theroastedroot.net/wp-content/uploads/2020/09/easy-vegetable-soup-1.jpg',
    items: [
      { name: 'Tomato Soup', price: 100, description: 'Creamy and tangy soup made from fresh, ripe tomatoes.' },
      { name: 'Veg Sweet Corn Soup', price: 100 },
      { name: 'Hot and Sour Soup', price: 100 },
      { name: 'Manchow Soup', price: 130, isBestseller: true, description: 'A spicy and hearty soup topped with crispy fried noodles.' },
      { name: 'Noodles Soup', price: 100 },
    ],
  },
  {
    id: 'burger',
    name: 'Burger',
    image: 'https://tse1.mm.bing.net/th/id/OIP.yQWKrcsv4B0EUukVirfHIAHaEK?r=0&w=1600&h=899&rs=1&pid=ImgDetMain&o=7&rm=3',
    items: [
      { name: 'Veg. Burger', price: 60 },
      { name: 'Veg. Cheese Burger', price: 80 },
      { name: 'Aloo Tikki Burger', price: 70, description: 'A crispy potato patty in a soft bun with our special sauce.' },
      { name: 'Double Tikki Burger', price: 100 },
      { name: 'Double Cheese Burger', price: 110, isBestseller: true, description: 'For the cheese lovers! Double patty, double cheese.' },
    ],
  },
  {
    id: 'chowmein',
    name: 'Chowmein',
    image: 'https://tse1.mm.bing.net/th/id/OIP.KSnQsx_5df2H9FgxETCE1QHaLH?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
    items: [
      { name: 'Veg. Chowmein', price: 80 },
      { name: 'Butter Veg Chowmein', price: 90 },
      { name: 'Manchurian Chowmein', price: 110 },
      { name: 'Paneer Chowmein', price: 130, isBestseller: true, description: 'Stir-fried noodles with succulent paneer cubes.' },
      { name: 'Schezwan Chowmein', price: 100, description: 'Spicy stir-fried noodles with a bold Schezwan kick.' },
    ],
  },
  {
    id: 'pizza',
    name: 'Pizza',
    image: 'https://tse2.mm.bing.net/th/id/OIP.MfhIfzrC6x6T1-szQkjtCgHaEo?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
    items: [
      { name: 'Veg. Cheese Pizza', price: 180 },
      { name: 'Onion Capsicum Pizza', price: 180 },
      { name: 'Paneer Tikka Pizza', price: 200, isBestseller: true, description: 'An Indian twist on a classic! Pizza topped with marinated paneer tikka.' },
      { name: 'Italian Pizza', price: 200 },
      { name: 'Mushroom Pizza', price: 180 },
      { name: 'Sweet Corn Pizza', price: 170 },
      { name: 'Tandoori Pizza', price: 220 },
      { name: 'Margarita Pizza', price: 220, description: 'The timeless classic with rich tomato sauce and mozzarella cheese.' },
    ],
  },
  {
    id: 'pasta',
    name: 'Pasta',
    image: 'https://tse1.mm.bing.net/th/id/OIP.8g_PETOWP1-rKeqIjred5AHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
    items: [
      { name: 'White Sauce Pasta', price: 130, description: 'Creamy and cheesy pasta cooked in a rich Alfredo sauce.' },
      { name: 'Red Sauce Pasta', price: 130, description: 'A tangy and flavorful pasta in a classic Arrabbiata sauce.' },
    ],
  },
  {
    id: 'chinese',
    name: 'Chinese',
    image: 'https://foodsguy.com/wp-content/uploads/2022/10/Assorted-Chinese-dishes-1170x846.jpg',
    items: [
      { name: 'Veg. Manchurian Dry', price: 90 },
      { name: 'Veg. Manchurian Gravy', price: 90 },
      { name: 'Paneer Chilli Dry', price: 130, isBestseller: true, description: 'Crispy paneer tossed in a spicy, tangy chili sauce.' },
      { name: 'Paneer Chilli Gravy', price: 140 },
      { name: 'Veg. Hakka Noodles', price: 130 },
      { name: 'Schezwan Noodles', price: 110 },
      { name: 'Mushroom Chilli Dry', price: 150 },
      { name: 'Mushroom Chilli Gravy', price: 150 },
      { name: 'Chinese Bhel', price: 120 },
      { name: 'Veg. Manchurian Rice', price: 150 },
      { name: 'Veg. Fried Rice', price: 140 },
      { name: 'Triple Fried Rice', price: 180 },
      { name: 'Chilli Milli', price: 140 },
      { name: 'Hara Bhara Kabab', price: 130 },
      { name: 'Paneer Tikka Snacks', price: 200 },
      { name: 'French Fries', price: 120 },
      { name: 'Garlic French Fries', price: 120 },
      { name: 'Peri Peri French Fries', price: 150 },
    ],
  },
  {
    id: 'maggi',
    name: 'Maggi',
    image: 'https://t4.ftcdn.net/jpg/03/67/31/89/360_F_367318954_4ttRBcmaa22q30OsJRqflxgCOd9dB9t6.jpg',
    items: [
      { name: 'Veg. Maggi', price: 70 },
      { name: 'Plain Maggi', price: 60, description: 'The ultimate comfort food, cooked to perfection.' },
      { name: 'Veg. Masala Maggi', price: 100 },
    ],
  },
  {
    id: 'momos',
    name: 'Momos',
    image: 'https://www.theroastedroot.net/wp-content/uploads/2020/09/easy-vegetable-soup-1.jpg',
    items: [
      { name: 'Veg Momos', price: 110 },
      { name: 'Fry Momos', price: 100 },
      { name: 'Kurkure Momos', price: 120 },
    ],
  },
  {
    id: 'snacks',
    name: 'Snacks',
    image: 'https://th.bing.com/th/id/R.7b7de2989ccc779db0e7fc77f1e1fa6b?rik=HNdxGzgSuxh11Q&riu=http%3a%2f%2frecipes.timesofindia.com%2fphoto%2f52416693.cms%3fimgsize%3d53280&ehk=fhVSmyLyPqhm2WGcvNs7i5cLR5BfvJAC15iXt2QEiPg%3d&risl=&pid=ImgRaw&r=0',
    items: [
      { name: 'Pav Bhaji', price: 70, isBestseller: true, description: 'A flavorful mash of mixed vegetables served with soft, buttered pav.' },
      { name: 'Extra Pav (1)', price: 10 },
      { name: 'Paneer Pakoda', price: 180 },
      { name: 'Veg. Pakoda', price: 140 },
      { name: 'Jain Pav Bhaji', price: 100 },
    ],
  },
  {
    id: 'south_indian',
    name: 'South Indian',
    image:'https://tse2.mm.bing.net/th/id/OIP.5HZWbK_56qfui_5LPjxfRwAAAA?r=0&w=474&h=272&rs=1&pid=ImgDetMain&o=7&rm=3' ,
    items: [
      { name: 'Masala Dosa', price: 70, isBestseller: true, description: 'A crispy rice crepe filled with a savory potato masala.' },
      { name: 'Plain Dosa', price: 70 },
      { name: 'Mysore Masala Dosa', price: 80 },
      { name: 'Paneer Dosa', price: 110 },
      { name: 'Cheese Paneer Dosa', price: 130 },
      { name: 'Cheese Dosa', price: 100 },
      { name: 'Onion Dosa', price: 90 },
      { name: 'Mix Uttapam', price: 120 },
      { name: 'Paneer Cheese Uttapam', price: 140 },
      { name: 'Veg. Uttapam', price: 100 },
      { name: 'Dahi Vada', price: 80 },
      { name: 'Idli Sambhar', price: 70 },
      { name: 'Fry Idli', price: 80 },
      { name: 'Masala Idli', price: 80 },
      { name: 'Sambhar Vada', price: 80 },
      { name: 'Kadhi Rice', price: 100 },
    ],
  },
  {
    id: 'punjabi',
    name: 'Punjabi',
    image: 'https://myfoodstory.com/wp-content/uploads/2021/10/Paneer-Butter-Masala-1-2.jpg',
    items: [
        { name: 'Kaju Masala', price: 230 },
        { name: 'Paneer Masala', price: 200 },
        { name: 'Paneer Tikka Masala', price: 190, description: 'Grilled paneer tikka simmered in a rich, creamy tomato gravy.' },
        { name: 'Kadai Paneer', price: 190 },
        { name: 'Shahi Paneer', price: 190 },
        { name: 'Handi Paneer', price: 200 },
        { name: 'Paneer Pasanda', price: 200 },
        { name: 'Paneer Bhurji', price: 220 },
        { name: 'Palak Paneer', price: 180 },
        { name: 'Mattar Paneer', price: 180 },
        { name: 'Malai Kofta', price: 190 },
        { name: 'Paneer Angara', price: 240 },
        { name: 'Paneer Lababdar', price: 220 },
        { name: 'Food Court Sp. Hungama', price: 250, isBestseller: true, description: 'Our signature dish - a spectacular mix of vegetables and paneer in a secret spicy gravy.' },
    ],
  },
  {
    id: 'marwadi special',
    name: 'Marwadi Special',
    image: '',
    items: [
      { name: 'SP. Haldi Sabji', price: 260},
      { name: 'Ker Sangri', price: 220 },
      { name: 'Garlic Chutney', price: 100 },
      { name: 'Mashroom Masala', price: 150  },
    ],
  },
    {
    id: 'Rajasthani Thali',
    name: 'Rajasthani Thali',
    image: '',
    items: [
      { name: 'Dal Fry,Sabji,Butter Milk,Rice,4 Roti,Papad,Salad,Chutney', price: 180},
    ],
  },
    {
    id: 'raita',
    name: 'Raita',
    image: '',
    items: [
      { name: 'Vegitable Raita', price: 120},
      { name: 'Bundi Raita', price: 100 },
      { name: 'Onion Raita', price: 100  },
      { name: 'Curd Fry', price: 120  },
      { name: 'Plain Curd', price: 70  },
    ],
  },
    {
    id: 'Dal',
    name: 'Dal',
    image: '',
    items: [
      { name: 'Dal Fry', price: 1200},
      { name: 'Dal Tadka', price: 130 },
      { name: 'Desi Dal Makhani', price: 140 },
      { name: 'Dehli Dal Makhani', price:180  },
    ],
  },
 
    {
    id: 'vegetable',
    name: 'Vegetable',
    image: 'https://cinnamonsnail.com/wp-content/uploads/2023/07/Chana-masala-04-720x1080.jpg',
    items: [
        { name: 'Veg. Makhani', price: 170 },
        { name: 'Mattar Masala', price: 160 },
        { name: 'Sev Onion', price: 150 },
        { name: 'Sev Tomato', price: 150 },
        { name: 'Sev Bhaji (With Milk)', price: 160 },
        { name: 'Mix Veg.', price: 160 },
        { name: 'Veg. Kolhapuri', price: 170, description: 'A spicy and aromatic mixed vegetable curry from Kolhapur.' },
        { name: 'Veg. Jaipuri', price: 180 },
        { name: 'Chana Masala', price: 160 },
        { name: 'Bhindi Masala / Fry', price: 150 },
        { name: 'Aloo Mattar', price: 140 },
        { name: 'Aloo Palak', price: 140 },
        { name: 'Aloo Gobhi', price: 140 },
        { name: 'Aloo Onion', price: 140 },
        { name: 'Dum Aloo', price: 150 },
    ],
  },
  {
    id: 'indian_breads',
    name: 'Indian Breads',
    image: 'https://tse2.mm.bing.net/th/id/OIP.H8HFen1gMXGitQs1Cn55nAHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3' ,
    items: [
        { name: 'Tandoori Roti', price: 15 },
        { name: 'Butter Tandoori Roti', price: 20 },
        { name: 'Plain Naan', price: 40 },
        { name: 'Butter Naan', price: 50 },
        { name: 'Laccha Paratha', price: 50 },
        { name: 'Cheese Garlic Naan', price: 60, isBestseller: true },
        { name: 'Plain Roti', price: 15 },
        { name: 'Butter Roti', price: 20 },
    ],
  },
  {
    id: 'rice',
    name: 'Rice',
    image: 'https://wallpaperaccess.com/full/1463596.jpg',
    items: [
        { name: 'Jeera Rice', price: 100 },
        { name: 'Masala Rice', price: 100 },
        { name: 'Veg. Pulao', price: 150 },
        { name: 'Kaju Pulao', price: 200 },
        { name: 'Mattar Pulao', price: 150 },
        { name: 'Veg. Hyderabadi Biryani', price: 190, isBestseller: true, description: 'Aromatic basmati rice cooked with mixed vegetables and exotic spices.' },
        { name: 'Veg. Biryani', price: 150 },
    ],
  },
  {
    id: 'Salad/Papad',
    name: 'Salad/Papad',
    image: '',
    items: [
      { name: 'Green Salad', price: 60 },
      { name: 'Kachumber Salad', price: 80 },
      { name: 'Roasted Papad', price: 30 },
      { name: 'Masala Papad', price: 50 },
      { name: 'Khichiya Plain', price: 50 },
      { name: 'Masala Papad', price: 100, },
    ],
  },
  {
    id: 'beverages',
    name: 'Juice and Tea',
    image: 'https://tse4.mm.bing.net/th/id/OIP.oy8M58KwSuyyvrquW5hFvQHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
    items: [
      { name: 'Mosambi Juice', price: 80 },
      { name: 'Orange Juice', price: 80 },
      { name: 'Pineapple Juice', price: 80 },
      { name: 'Mix Fruit Juice', price: 90 },
      { name: 'Masala Tea', price: 20 },
      { name: 'Sp. Kulhad Tea', price: 20, isBestseller: true },
      { name: 'Coffee', price: 30 },
    ],
  },
  {
    id: 'lassi',
    name: 'Lassi',
    image: '',
    items: [
      { name: 'SP> Food Court Lassi', price: 80 },
      { name: 'Sweet Lassi', price: 60 },
      { name: 'Masala Butter Lassi', price: 70 },
      { name: 'Plain Butter Milk', price: 20 },
      { name: 'Masala Butter Milk', price: 30 },
    ],
  },
  {
    id: 'Chocolate shakes',
    name: 'Chocolate Shakes',
    image: '',
    items: [
      { name: 'Chocolate Shake', price: 70 },
      { name: 'Chocolate Shake (With Ice Cream)', price: 100 },
      { name: 'Cold Coffee', price: 70 },
      { name: 'Thick Chocolate Shake', price: 100 },
     ],
  },
  {
    id: 'ice cream shakes',
    name: 'Ice Cream Shakes',
    image: 'https://tse1.mm.bing.net/th/id/OIP.RDmlNxzuCRhBgZPtAv-S2QHaEJ?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
    items: [
      { name: 'Pineapple Shake', price: 80 },
      { name: 'Strawberry Shake', price: 80 },
      { name: 'Mango Shake', price: 80 },
      { name: 'Chiku Shake', price: 80 },
      { name: 'Papita Shake', price: 80 },
      { name: 'Milk Rose Shake', price: 80 },
      { name: 'Vanilla Shake', price: 100 },
      { name: 'Butter Scotch Shake', price: 100 },

      { name: 'Kaju Anjeer Shake', price: 180, isBestseller: true, description: 'A rich and healthy shake made from cashews and figs.' },
      { name: 'Dry Fruit Shake', price: 200 },
      { name: 'Anjeer Shake', price: 190 },
      { name: 'Kit Kat Shake', price: 100 },
      { name: 'Orio Shake', price: 100 },
      { name: 'Kesar Pista Shake', price: 120 },
      { name: 'Labalab Shake', price: 120 },
      { name: 'Jhamajham Shake', price: 110 },
    ],
  },
  {
    id: 'cold drinks',
    name: 'Cold Drinks',
    image: '',
    items: [
     { name: 'Cold Drinks', price: MRP + 10 Extra,  },
     { name: 'Water Bottle', price: 20 },      
    ],
  },
];
